language: python
sudo: required
python:
- '2.7'
cache: pip
install:
- pip install cloudpassage
- pip install flake8
- pip install gitpython
- pip install json2html
script:
# install the Halo agent
# update apt repositories
- sudo apt-get update > /dev/null

# install curl
- sudo apt-get -y install curl

# add CloudPassage repository
- echo 'deb https://production.packages.cloudpassage.com/debian debian main' | sudo tee /etc/apt/sources.list.d/cloudpassage.list > /dev/null

# import CloudPassage public key
- curl https://production.packages.cloudpassage.com/cloudpassage.packages.key | sudo apt-key add -

# update apt repositories
- sudo apt-get update > /dev/null

# install the agent
- sudo apt-get -y install cphalo

# configure agent key
- sudo /opt/cloudpassage/bin/configure --agent-key=$HALO_AGENT_KEY

#  start the agent for the first time
- sudo /etc/init.d/cphalod start

# get build workload ip
- server_ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
- sed -i -e "1,/<server_ip>/s/<server_ip>/$server_ip/" app/sva_scan_examples/config_helper.py

- cd app/test/style/
- python test_style_flake8.py
- cd ../unit/
- python test_config_helper.py
- python test_sva_scan_examples.py
env:
  global:
  # halo API keys
  - secure: NL3bAJXDosr4bbr3/+NYomf9rZGQ3rTieOnZTqecn0VqKmVbolEpRXgYLtxh9n2cDWuBv1d1HmZ2f2MQ6CaD9EJk2X8RSTEJSphy/8fZoRSGRJvLy/0GzIF2IzvxibTyNZSmhwzC3SpX00/Zgv+fvkVkcHeQHJC1ogf602rnek7dRgOCUZhxsliEpE+GKacvkhcZqIe483GPEsV/dkWVfilq65IBtR8/lJifS83NvgQIgTsSQlckya3jbs4uXgwQSd9U5nQu9GwpOd55soUI7CD4JieAUXJXVlBO2pch20WiO4Z2NcXhCgrlVqvIcYACogM3hPmqyNNMUvpij5d28YQYP7JjyhftWwC8Wfx+oceLkSzYOcF20f4ahCCG2HoOMkl/nU0SOIaXQU+ZByUN4QqnVSOu67Z+EiYo0+Ptod0Qh/1qWbAeBMFugUjC4QOxJN5hZh0BOcm0FL0aHNFe2Nd/JpMVGJhzAFP1jpe4Lp6E2wWTRSSiIq5cxoSBDS6jOI09k+7nxs/s4/grHd0NwpqxamQ7ByPmRDAOMeom/EDgbigKY1rf8oRQeppf7m+/gkpQ7FnuKY6zzG0F2ykcDCIXyMpjfIvbrPN9fSULCaCXGkb07nrJAUlEhnGG2qcUh/EBTHjUhLiextxMrYnEWTzg2vGo7RAjdtAI4zfJHxw=
  - secure: H8VeGNYID3V9w1h9Us1sxv56Thy53RWZJlv5Zx551uTq3gEz6TXqmJ026na2Vwlj+lWowHsNV4UVIvpBNRqtR/j7BZT3bEjEi1TLkiDWvmxdDmUlQQ+/jQLZFlrz5NWSjrZO4w0dZS8H6huanYtugxJq71+d/tBIGsSyty6V34HqZLMVrlavESUyTZ33iO7arI7TznwhQH90LsLJ5AgMIjcGb8vQishC7IhY7WaxezUl7b+98X1lwbJ7fzQ7CWoysJtJac1vSHvHrO6Wwhyjq/60yXII4kgbBAwEJnN/eS2WU3u3rRu+njP8ODNGfiyecYZhrjjH/HZYTzClyKBdGQXaNvrUB7AbKoTUNtPEM+Kb4+S9BK/1e3MRnuAibZYh5tYO8DRjCVgnZAi9R1dnaFG0RgdsWv5M8wyErxMUu71o668BDWgasT1sgeR1LEUTcNbTzHxRkBDcYgyp+8DtZ0mFYS40+X10JXux8vKW3eByilTtjFBP7E2mWseQeCoS1unYN5pLFQZkfRd3Kxay9995Cw1JD0EJIEHhdDPK7OqfBxhI2uScL8zZp5Og3l9wYNKCdgL0sSjgzMXQ1pgCTHJLvU51ucNMBeV8bcy55Lx32EjNasVp+L3MMRSOvUGhHMMqCe4QGZ3Ke9EJssEp4wJH4acoAvhTazAuWJertNQ=
  # halo agent key
  - secure: "Vum6vIyiFNksjtEh0ECuGoqmezkrDqfrYCd27IrE5XYe1rvFrkO1khp0Y0M/sTwq+aVNm0Sby69D7Z14JA3U8DnU9ukRi9ihL8sSic0hJ5nU//mG2aX0DnYZ6IVnRd/1iznZyyneWjowll+D/hZUE+XMVkaWgS5gqHEogA03V8O7eYt1z+1/UbiWiUED/+6SKlse6dnEptxtP69qDSCrcn2nyAXA50ih21YlBUUG70K/wCuwsqjs1jV8XtWpi491nM0KARArZry/jKbHPpegFRCcuT4PCFz77BEJSnIo5+hVFivrMYP1g9Ot9AuOwSxgRSC4Pn4T2KvI7JPf6MkovlBl/+FacaPGBxZwMqKwQ/JWT0XumWJ/E7wInWaW8HVfEFXPNfbygMbIpndyQMeO0aOh+uYEQzPfLne8oADkSJAfTFHuC8PtVJ7/Xkutom/wtC49Yl0axddX0yWCd0fPfyG+XRySg/Wg4NVAKZ0LF0M79adMH2xYC/N80OG8IK16xErzMJspUe/rTke/gvo73spaBjzE27AjWsLvNswoQ+rJUT04lGgtRVk1hrw9Ywy6tAuwtha0Ihwq+yaWwq0wjDWKGkcowbpZ/kOCsAXUSJhv3AIMkErLDPnEbj9qNt1vK3ZbO2/cEaAuUfPlz8VESKp1u1PVg8OFfKEc2hueTXU="
