language: python
sudo: required
python:
- '2.7'
cache: pip
install:
- pip install cloudpassage
- pip install flake8
script:
- sudo /etc/init.d/cphalod start
- cd app/test/style/
- python test_style_flake8.py
- cd ../unit/
- python test_config_helper.py
env:
  global: 
  matrix:
  - secure: NL3bAJXDosr4bbr3/+NYomf9rZGQ3rTieOnZTqecn0VqKmVbolEpRXgYLtxh9n2cDWuBv1d1HmZ2f2MQ6CaD9EJk2X8RSTEJSphy/8fZoRSGRJvLy/0GzIF2IzvxibTyNZSmhwzC3SpX00/Zgv+fvkVkcHeQHJC1ogf602rnek7dRgOCUZhxsliEpE+GKacvkhcZqIe483GPEsV/dkWVfilq65IBtR8/lJifS83NvgQIgTsSQlckya3jbs4uXgwQSd9U5nQu9GwpOd55soUI7CD4JieAUXJXVlBO2pch20WiO4Z2NcXhCgrlVqvIcYACogM3hPmqyNNMUvpij5d28YQYP7JjyhftWwC8Wfx+oceLkSzYOcF20f4ahCCG2HoOMkl/nU0SOIaXQU+ZByUN4QqnVSOu67Z+EiYo0+Ptod0Qh/1qWbAeBMFugUjC4QOxJN5hZh0BOcm0FL0aHNFe2Nd/JpMVGJhzAFP1jpe4Lp6E2wWTRSSiIq5cxoSBDS6jOI09k+7nxs/s4/grHd0NwpqxamQ7ByPmRDAOMeom/EDgbigKY1rf8oRQeppf7m+/gkpQ7FnuKY6zzG0F2ykcDCIXyMpjfIvbrPN9fSULCaCXGkb07nrJAUlEhnGG2qcUh/EBTHjUhLiextxMrYnEWTzg2vGo7RAjdtAI4zfJHxw=
  - secure: H8VeGNYID3V9w1h9Us1sxv56Thy53RWZJlv5Zx551uTq3gEz6TXqmJ026na2Vwlj+lWowHsNV4UVIvpBNRqtR/j7BZT3bEjEi1TLkiDWvmxdDmUlQQ+/jQLZFlrz5NWSjrZO4w0dZS8H6huanYtugxJq71+d/tBIGsSyty6V34HqZLMVrlavESUyTZ33iO7arI7TznwhQH90LsLJ5AgMIjcGb8vQishC7IhY7WaxezUl7b+98X1lwbJ7fzQ7CWoysJtJac1vSHvHrO6Wwhyjq/60yXII4kgbBAwEJnN/eS2WU3u3rRu+njP8ODNGfiyecYZhrjjH/HZYTzClyKBdGQXaNvrUB7AbKoTUNtPEM+Kb4+S9BK/1e3MRnuAibZYh5tYO8DRjCVgnZAi9R1dnaFG0RgdsWv5M8wyErxMUu71o668BDWgasT1sgeR1LEUTcNbTzHxRkBDcYgyp+8DtZ0mFYS40+X10JXux8vKW3eByilTtjFBP7E2mWseQeCoS1unYN5pLFQZkfRd3Kxay9995Cw1JD0EJIEHhdDPK7OqfBxhI2uScL8zZp5Og3l9wYNKCdgL0sSjgzMXQ1pgCTHJLvU51ucNMBeV8bcy55Lx32EjNasVp+L3MMRSOvUGhHMMqCe4QGZ3Ke9EJssEp4wJH4acoAvhTazAuWJertNQ=
